apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: book
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: book
        tier: backend
    spec:
      containers:
      - name: rest-example
        image: jotka/rest-example
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080